apiVersion: v1
kind: Service
metadata:
  name: oauth-demo-db
  namespace: observability
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  type: ClusterIP
  selector:
    app: oauth-demo-db
